apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    type: NodePort
    ports:
        - port: 80
          name: wordpress
          targetPort: 80
    selector:
        app: wordpress

---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    ports:
        - port: 3306
          name: db
    type: ClusterIP
    selector:
        app: mysql
